### ISSUE TITLE
Reinstantiate search-algorithms on stackage

### ISSUE THREAD

**Issue by cohomology** [devonhollowood/search-algorithms#12]
Hi,

at the moment, search-algorithms is last in LTS 12.26. It is disabled in build-constraints.yml. I guess the reason is not anymore present, right?

Best regards,
Kilian.

**Comment by devonhollowood** [comment]
Thank you for bringing this to my attention, and sorry for the slow response. I've put up a pull request to re-enable this package at commercialhaskell/stackage/pull/5018
