### ISSUE TITLE
...any chance of monadic versions?

### ISSUE THREAD

**Issue by phlummox** [devonhollowood/search-algorithms#7]
I see the [astar] package has both a standard and monadic version of the astar function. Is it likely you might add similar functions to `search-algorithms`? (I do like your approach of factoring out the core of the search algorithms, btw.)

[astar]: https://hackage.haskell.org/package/astar-0.3.0.0

I'm just about to roll my own, but thought I'd mention this in case you were interested.

**Comment by devonhollowood** [comment]
Yeah monadic versions are definitely on my to-do list! If you write a monadic version of any / all of the algorithms, and want to submit it as a pull request, that would be great. Otherwise I'll probably get around to it sometime this summer.
